// ACTIONS project
export const NEW_PROJECT = 'NEW_PROJECT' as const;
export const LOAD_PROJECT = 'LOAD_PROJECT' as const;
export const SAVE_PROJECT = 'SAVE_PROJECT' as const;
export const OPEN_CATALOG = 'OPEN_CATALOG' as const;
export const SELECT_TOOL_EDIT = 'SELECT_TOOL_EDIT' as const;
export const UNSELECT_ALL = 'UNSELECT_ALL' as const;
export const SET_PROPERTIES = 'SET_PROPERTIES' as const;
export const SET_ITEMS_ATTRIBUTES = 'SET_ITEMS_ATTRIBUTES' as const;
export const SET_LINES_ATTRIBUTES = 'SET_LINES_ATTRIBUTES' as const;
export const SET_HOLES_ATTRIBUTES = 'SET_HOLES_ATTRIBUTES' as const;
export const REMOVE = 'REMOVE' as const;
export const UNDO = 'UNDO' as const;
export const REDO = 'REDO' as const;
export const ROLLBACK = 'ROLLBACK' as const;
export const SET_PROJECT_PROPERTIES = 'SET_PROJECT_PROPERTIES' as const;
export const OPEN_PROJECT_CONFIGURATOR = 'OPEN_PROJECT_CONFIGURATOR' as const;
export const INIT_CATALOG = 'INIT_CATALOG' as const;
export const UPDATE_MOUSE_COORDS = 'UPDATE_MOUSE_COORDS' as const;
export const UPDATE_ZOOM_SCALE = 'UPDATE_ZOOM_SCALE' as const;
export const TOGGLE_SNAP = 'TOGGLE_SNAP' as const;
export const CHANGE_CATALOG_PAGE = 'CHANGE_CATALOG_PAGE' as const;
export const GO_BACK_TO_CATALOG_PAGE = 'GO_BACK_TO_CATALOG_PAGE' as const;
export const THROW_ERROR = 'THROW_ERROR' as const;
export const THROW_WARNING = 'THROW_WARNING' as const;
export const COPY_PROPERTIES = 'COPY_PROPERTIES' as const;
export const PASTE_PROPERTIES = 'PASTE_PROPERTIES' as const;
export const PUSH_LAST_SELECTED_CATALOG_ELEMENT_TO_HISTORY = 'PUSH_LAST_SELECTED_CATALOG_ELEMENT_TO_HISTORY' as const;
export const ALTERATE_STATE = 'ALTERATE_STATE' as const;
export const SET_MODE = 'SET_MODE' as const;
export const ADD_HORIZONTAL_GUIDE = 'ADD_HORIZONTAL_GUIDE' as const;
export const ADD_VERTICAL_GUIDE = 'ADD_VERTICAL_GUIDE' as const;
export const ADD_CIRCULAR_GUIDE = 'ADD_CIRCULAR_GUIDE' as const;
export const REMOVE_HORIZONTAL_GUIDE = 'REMOVE_HORIZONTAL_GUIDE' as const;
export const REMOVE_VERTICAL_GUIDE = 'REMOVE_VERTICAL_GUIDE' as const;
export const REMOVE_CIRCULAR_GUIDE = 'REMOVE_CIRCULAR_GUIDE' as const;

// ACTIONS viewer2D
export const UPDATE_2D_CAMERA = 'UPDATE_2D_CAMERA' as const;
export const SELECT_TOOL_ZOOM_IN = 'SELECT_TOOL_ZOOM_IN' as const;
export const SELECT_TOOL_ZOOM_OUT = 'SELECT_TOOL_ZOOM_OUT' as const;
export const SELECT_TOOL_PAN = 'SELECT_TOOL_PAN' as const;
export const FIT_SELECTION = 'FIT_SELECTION' as const;

//ACTIONS viewer3D
export const SELECT_TOOL_3D_VIEW = 'SELECT_TOOL_3D_VIEW' as const;
export const SELECT_TOOL_3D_FIRST_PERSON = 'SELECT_TOOL_3D_FIRST_PERSON' as const;

//ACTIONS items
export const SELECT_TOOL_DRAWING_ITEM = 'SELECT_TOOL_DRAWING_ITEM' as const;
export const UPDATE_DRAWING_ITEM = 'UPDATE_DRAWING_ITEM' as const;
export const END_DRAWING_ITEM = 'END_DRAWING_ITEM' as const;
export const BEGIN_DRAGGING_ITEM = 'BEGIN_DRAGGING_ITEM' as const;
export const UPDATE_DRAGGING_ITEM = 'UPDATE_DRAGGING_ITEM' as const;
export const END_DRAGGING_ITEM = 'END_DRAGGING_ITEM' as const;
export const BEGIN_ROTATING_ITEM = 'BEGIN_ROTATING_ITEM' as const;
export const UPDATE_ROTATING_ITEM = 'UPDATE_ROTATING_ITEM' as const;
export const END_ROTATING_ITEM = 'END_ROTATING_ITEM' as const;

//ACTIONS groups
export const ADD_GROUP = 'ADD_GROUP' as const;
export const ADD_GROUP_FROM_SELECTED = 'ADD_GROUP_FROM_SELECTED' as const;
export const SELECT_GROUP = 'SELECT_GROUP' as const;
export const UNSELECT_GROUP = 'UNSELECT_GROUP' as const;
export const ADD_TO_GROUP = 'ADD_TO_GROUP' as const;
export const REMOVE_FROM_GROUP = 'REMOVE_FROM_GROUP' as const;
export const SET_GROUP_PROPERTIES = 'SET_GROUP_PROPERTIES' as const;
export const SET_GROUP_ATTRIBUTES = 'SET_GROUP_ATTRIBUTES' as const;
export const SET_GROUP_BARYCENTER = 'SET_GROUP_BARYCENTER' as const;
export const REMOVE_GROUP = 'REMOVE_GROUP' as const;
export const REMOVE_GROUP_AND_DELETE_ELEMENTS = 'REMOVE_GROUP_AND_DELETE_ELEMENTS' as const;
export const GROUP_TRANSLATE = 'GROUP_TRANSLATE' as const;
export const GROUP_ROTATE = 'GROUP_ROTATE' as const;

//ACTION drawings
export const SELECT_HOLE = 'SELECT_HOLE' as const;
export const SELECT_AREA = 'SELECT_AREA' as const;
export const SELECT_ITEM = 'SELECT_ITEM' as const;
export const SELECT_LINE = 'SELECT_LINE' as const;
export const SELECT_TOOL_DRAWING_LINE = 'SELECT_TOOL_DRAWING_LINE' as const;
export const BEGIN_DRAWING_LINE = 'BEGIN_DRAWING_LINE' as const;
export const UPDATE_DRAWING_LINE = 'UPDATE_DRAWING_LINE' as const;
export const END_DRAWING_LINE = 'END_DRAWING_LINE' as const;
export const SELECT_TOOL_DRAWING_HOLE = 'SELECT_TOOL_DRAWING_HOLE' as const;
export const UPDATE_DRAWING_HOLE = 'UPDATE_DRAWING_HOLE' as const; //SHOULD BE SLPITTED IN BEGIN_DRAWING_HOLE AND UPDATE_DRAWING_HOLE
export const END_DRAWING_HOLE = 'END_DRAWING_HOLE' as const;
export const BEGIN_DRAGGING_LINE = 'BEGIN_DRAGGING_LINE' as const;
export const UPDATE_DRAGGING_LINE = 'UPDATE_DRAGGING_LINE' as const;
export const END_DRAGGING_LINE = 'END_DRAGGING_LINE' as const;
export const SELECT_TOOL_UPLOAD_IMAGE = 'SELECT_TOOL_UPLOAD_IMAGE' as const;
export const BEGIN_UPLOADING_IMAGE = 'BEGIN_UPLOADING_IMAGE' as const;
export const END_UPLOADING_IMAGE = 'END_UPLOADING_IMAGE' as const;
export const BEGIN_FITTING_IMAGE = 'BEGIN_FITTING_IMAGE' as const;
export const END_FITTING_IMAGE = 'END_FITTING_IMAGE' as const;
export const BEGIN_DRAGGING_HOLE = 'BEGIN_DRAGGING_HOLE' as const;
export const UPDATE_DRAGGING_HOLE = 'UPDATE_DRAGGING_HOLE' as const;
export const END_DRAGGING_HOLE = 'END_DRAGGING_HOLE' as const;

//ACTIONS vertices
export const BEGIN_DRAGGING_VERTEX = 'BEGIN_DRAGGING_VERTEX' as const;
export const UPDATE_DRAGGING_VERTEX = 'UPDATE_DRAGGING_VERTEX' as const;
export const END_DRAGGING_VERTEX = 'END_DRAGGING_VERTEX' as const;

//ACTIONS scene
export const SET_LAYER_PROPERTIES = 'SET_LAYER_PROPERTIES' as const;
export const ADD_LAYER = 'ADD_LAYER' as const;
export const SELECT_LAYER = 'SELECT_LAYER' as const;
export const REMOVE_LAYER = 'REMOVE_LAYER' as const;

//GROUPING ACTIONS
export const PROJECT_ACTIONS = {
  NEW_PROJECT,
  LOAD_PROJECT,
  SAVE_PROJECT,
  OPEN_CATALOG,
  SELECT_TOOL_EDIT,
  UNSELECT_ALL,
  SET_PROPERTIES,
  SET_ITEMS_ATTRIBUTES,
  SET_LINES_ATTRIBUTES,
  SET_HOLES_ATTRIBUTES,
  REMOVE,
  UNDO,
  REDO,
  ROLLBACK,
  SET_PROJECT_PROPERTIES,
  OPEN_PROJECT_CONFIGURATOR,
  INIT_CATALOG,
  UPDATE_MOUSE_COORDS,
  UPDATE_ZOOM_SCALE,
  TOGGLE_SNAP,
  CHANGE_CATALOG_PAGE,
  GO_BACK_TO_CATALOG_PAGE,
  THROW_ERROR,
  THROW_WARNING,
  COPY_PROPERTIES,
  PASTE_PROPERTIES,
  PUSH_LAST_SELECTED_CATALOG_ELEMENT_TO_HISTORY,
  ALTERATE_STATE,
  SET_MODE,
  ADD_HORIZONTAL_GUIDE,
  ADD_VERTICAL_GUIDE,
  ADD_CIRCULAR_GUIDE,
  REMOVE_HORIZONTAL_GUIDE,
  REMOVE_VERTICAL_GUIDE,
  REMOVE_CIRCULAR_GUIDE
} as const;

export const VIEWER2D_ACTIONS = {
  SELECT_TOOL_ZOOM_IN,
  SELECT_TOOL_ZOOM_OUT,
  SELECT_TOOL_PAN,
  UPDATE_2D_CAMERA,
  FIT_SELECTION
} as const;

export const VIEWER3D_ACTIONS = {
  SELECT_TOOL_3D_VIEW,
  SELECT_TOOL_3D_FIRST_PERSON
} as const;

export const ITEMS_ACTIONS = {
  SELECT_ITEM,
  SELECT_TOOL_DRAWING_ITEM,
  UPDATE_DRAWING_ITEM,
  END_DRAWING_ITEM,
  BEGIN_DRAGGING_ITEM,
  UPDATE_DRAGGING_ITEM,
  END_DRAGGING_ITEM,
  BEGIN_ROTATING_ITEM,
  UPDATE_ROTATING_ITEM,
  END_ROTATING_ITEM
} as const;

export const HOLE_ACTIONS = {
  SELECT_HOLE,
  SELECT_TOOL_DRAWING_HOLE,
  UPDATE_DRAWING_HOLE,
  END_DRAWING_HOLE,
  BEGIN_DRAGGING_HOLE,
  UPDATE_DRAGGING_HOLE,
  END_DRAGGING_HOLE
} as const;

export const LINE_ACTIONS = {
  SELECT_LINE,
  SELECT_TOOL_DRAWING_LINE,
  BEGIN_DRAWING_LINE,
  UPDATE_DRAWING_LINE,
  END_DRAWING_LINE,
  BEGIN_DRAGGING_LINE,
  UPDATE_DRAGGING_LINE,
  END_DRAGGING_LINE
} as const;

export const AREA_ACTIONS = {
  SELECT_AREA
} as const;

export const GROUP_ACTIONS = {
  ADD_GROUP,
  ADD_GROUP_FROM_SELECTED,
  SELECT_GROUP,
  UNSELECT_GROUP,
  ADD_TO_GROUP,
  REMOVE_FROM_GROUP,
  SET_GROUP_PROPERTIES,
  SET_GROUP_ATTRIBUTES,
  SET_GROUP_BARYCENTER,
  REMOVE_GROUP,
  REMOVE_GROUP_AND_DELETE_ELEMENTS,
  GROUP_TRANSLATE,
  GROUP_ROTATE
} as const;

export const SCENE_ACTIONS = {
  ADD_LAYER,
  SET_LAYER_PROPERTIES,
  SELECT_LAYER,
  REMOVE_LAYER
} as const;

export const VERTEX_ACTIONS = {
  BEGIN_DRAGGING_VERTEX,
  UPDATE_DRAGGING_VERTEX,
  END_DRAGGING_VERTEX
} as const;

//MODES
export const MODE_IDLE = 'MODE_IDLE' as const;
export const MODE_2D_ZOOM_IN = 'MODE_2D_ZOOM_IN' as const;
export const MODE_2D_ZOOM_OUT = 'MODE_2D_ZOOM_OUT' as const;
export const MODE_2D_PAN = 'MODE_2D_PAN' as const;
export const MODE_3D_VIEW = 'MODE_3D_VIEW' as const;
export const MODE_3D_FIRST_PERSON = 'MODE_3D_FIRST_PERSON' as const;
export const MODE_WAITING_DRAWING_LINE = 'MODE_WAITING_DRAWING_LINE' as const;
export const MODE_DRAGGING_LINE = 'MODE_DRAGGING_LINE' as const;
export const MODE_DRAGGING_VERTEX = 'MODE_DRAGGING_VERTEX' as const;
export const MODE_DRAGGING_ITEM = 'MODE_DRAGGING_ITEM' as const;
export const MODE_DRAGGING_HOLE = 'MODE_DRAGGING_HOLE' as const;
export const MODE_DRAWING_LINE = 'MODE_DRAWING_LINE' as const;
export const MODE_DRAWING_HOLE = 'MODE_DRAWING_HOLE' as const;
export const MODE_DRAWING_ITEM = 'MODE_DRAWING_ITEM' as const;
export const MODE_ROTATING_ITEM = 'MODE_ROTATING_ITEM' as const;
export const MODE_UPLOADING_IMAGE = 'MODE_UPLOADING_IMAGE' as const;
export const MODE_FITTING_IMAGE = 'MODE_FITTING_IMAGE' as const;
export const MODE_VIEWING_CATALOG = 'MODE_VIEWING_CATALOG' as const;
export const MODE_CONFIGURING_PROJECT = 'MODE_CONFIGURING_PROJECT' as const;

export const MODE_SNAPPING: readonly string[] = [
  MODE_IDLE, MODE_2D_ZOOM_IN, MODE_2D_ZOOM_OUT, MODE_2D_PAN,
  MODE_WAITING_DRAWING_LINE, MODE_DRAWING_LINE, MODE_DRAWING_HOLE,
  MODE_DRAWING_ITEM, MODE_DRAGGING_LINE, MODE_DRAGGING_VERTEX,
  MODE_DRAGGING_ITEM, MODE_DRAGGING_HOLE, MODE_FITTING_IMAGE,
  MODE_UPLOADING_IMAGE, MODE_ROTATING_ITEM
];

//UNITS
export const UNIT_MILLIMETER = 'mm' as const;
export const UNIT_CENTIMETER = 'cm' as const;
export const UNIT_METER = 'm' as const;
export const UNIT_INCH = 'in' as const;
export const UNIT_FOOT = 'ft' as const;
export const UNIT_MILE = 'mi' as const;

export const UNITS_LENGTH: readonly string[] = [
  UNIT_MILLIMETER,
  UNIT_CENTIMETER,
  UNIT_METER,
  UNIT_INCH,
  UNIT_FOOT,
  UNIT_MILE
];

export const EPSILON: number = 1e-6;

export const KEYBOARD_BUTTON_CODE: Record<string, number> = {
  DELETE: 46,
  BACKSPACE: 8,
  ESC: 27,
  Z: 90,
  ALT: 18,
  C: 67,
  V: 86,
  CTRL: 17,
  ENTER: 13,
  TAB: 9
};
