/**
 * Display-only helpers that turn raw internal element names/ids
 * ("wall_99ysl9u9y37", "sedia_e7606d1c…") into friendly labels
 * ("Wall 3", "Chair 1") in the presentation layer.
 *
 * Store data is never modified — ordinals are computed from the layer's
 * element insertion order, so they are stable for a given scene.
 */

interface DisplayableElement {
  id: string;
  type?: string;
  name?: string;
}

/** "sofa_l" -> "Sofa L", "tv-stand" -> "Tv Stand" */
export function prettyTypeName(raw: string): string {
  if (!raw) return "Element";
  return raw
    .replace(/[-_]+/g, " ")
    .trim()
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/**
 * An element's name is auto-generated when it still looks like
 * `${type}_<id>`. If the user renamed it, we honour the custom name.
 */
export function isAutoGeneratedName(element: DisplayableElement): boolean {
  const name = element.name ?? "";
  const type = element.type ?? "";
  if (!name) return true;
  return name.startsWith(`${type}_`) || /^[a-z0-9-]+_[a-z0-9-]{6,}$/i.test(name);
}

/**
 * Builds a map of elementId -> friendly display name for one element
 * collection (e.g. a layer's lines, items, holes or areas). The ordinal
 * is per type and follows the collection's insertion order.
 */
export function buildDisplayNames(
  elements: Record<string, DisplayableElement>,
): Record<string, string> {
  const counters: Record<string, number> = {};
  const result: Record<string, string> = {};

  for (const [id, element] of Object.entries(elements)) {
    const typeKey = element.type || element.name?.split("_")[0] || "element";
    counters[typeKey] = (counters[typeKey] || 0) + 1;

    result[id] = isAutoGeneratedName(element)
      ? `${prettyTypeName(typeKey)} ${counters[typeKey]}`
      : (element.name as string);
  }

  return result;
}

/** Friendly name for a single element given its collection. */
export function displayNameFor(
  element: DisplayableElement,
  collection: Record<string, DisplayableElement> | undefined,
): string {
  if (!isAutoGeneratedName(element)) return element.name as string;
  if (collection && element.id in collection) {
    const names = buildDisplayNames(collection);
    if (names[element.id]) return names[element.id];
  }
  return prettyTypeName(element.type || element.name?.split("_")[0] || "Element");
}

interface VertexLike {
  x: number;
  y: number;
}

interface AreaLike extends DisplayableElement {
  vertices: string[];
  holes: string[];
}

interface LayerLike {
  vertices: Record<string, VertexLike>;
  areas: Record<string, AreaLike>;
}

function ringArea(ring: VertexLike[]): number {
  let sum = 0;
  for (let i = 0; i < ring.length; i++) {
    const a = ring[i];
    const b = ring[(i + 1) % ring.length];
    sum += a.x * b.y - b.x * a.y;
  }
  return Math.abs(sum) / 2;
}

function ringFromVertexIDs(vertexIDs: string[], layer: LayerLike): VertexLike[] {
  const ring: VertexLike[] = [];
  for (const vertexID of vertexIDs) {
    const vertex = layer.vertices[vertexID];
    if (vertex) ring.push(vertex);
  }
  return ring;
}

/** Area size in scene units² (cm²), holes subtracted. */
export function computeAreaSize(area: AreaLike, layer: LayerLike): number {
  const outer = ringFromVertexIDs(area.vertices, layer);
  if (outer.length < 3) return 0;
  let size = ringArea(outer);
  for (const holeID of area.holes || []) {
    const hole = layer.areas[holeID];
    if (!hole) continue;
    const holeRing = ringFromVertexIDs(hole.vertices, layer);
    if (holeRing.length >= 3) size -= ringArea(holeRing);
  }
  return size;
}

/** "37.44 m²" from a cm² size. */
export function formatAreaSize(sizeCm2: number): string {
  return `${(sizeCm2 / 10000).toFixed(2)} m²`;
}
